CREATE TABLE "GCG_4117_WC_Hour_Log"(
 "REC_ID" INTEGER,
 "MACHINE" CHAR(4),
 "CHARGE_DATE" DATE,
 "EMP_TIME_START" TIME,
 "EMP_TIME_END" TIME,
 "WC_HOURS_START" DECIMAL(10,4),
 "WC_HOURS_END" DECIMAL(10,4),
 "OPERATION_SEQ" CHAR(6),
 "EMPLOYEE" CHAR(5),
 "JOB_SUFFIX" CHAR(9));
